-- 1. Attrition rate (%) by Department and Job Role.

SELECT CAST(ROUND(((COUNT(ATTRITION)/237.0)*100),2) AS DECIMAL(5,2)) AS 'ATTRITION_RATE (%)', DEPARTMENT, JOBROLE 
FROM EMP_ATTRITION
WHERE ATTRITION = 1
GROUP BY DEPARTMENT, JOBROLE 
ORDER BY 'ATTRITION_RATE (%)' DESC

SELECT COUNT(ATTRITION) AS ATTRITION_COUNT, DEPARTMENT, JOBROLE 
FROM EMP_ATTRITION
WHERE ATTRITION = 1
GROUP BY DEPARTMENT, JOBROLE 
ORDER BY ATTRITION_COUNT DESC

-- 2. Average Years At Company for attrited vs. retained employees.

(SELECT AVG(TOTALWORKINGYEARS) AS AVG_WORKING_YEARS, ATTRITION 
FROM EMP_ATTRITION
WHERE ATTRITION = 1
GROUP BY ATTRITION)

UNION

(SELECT AVG(TOTALWORKINGYEARS) AS AVG_WORKING_YEARS, ATTRITION 
FROM EMP_ATTRITION
WHERE ATTRITION = 0
GROUP BY ATTRITION)

-- 3. Do employees with OverTime have higher attrition rates?

SELECT COUNT(OVERTIME) AS EMP_WORKING_OVERTIME, ATTRITION FROM EMP_ATTRITION
WHERE OVERTIME = 1
GROUP BY ATTRITION
ORDER BY EMP_WORKING_OVERTIME

-- 4. Which EducationField has the highest attrition?

SELECT EducationField, COUNT(ATTRITION) AS ATTRITION_COUNT 
FROM EMP_ATTRITION
WHERE ATTRITION = 1
GROUP BY EDUCATIONFIELD
ORDER BY ATTRITION_COUNT DESC

-- 5. Average income by JobLevel and JobRole.

SELECT JOBLEVEL, JOBROLE, AVG(MONTHLYINCOME) AS AVERGE_INCOME
FROM EMP_ATTRITION
GROUP BY JOBLEVEL, JOBROLE
ORDER BY JOBLEVEL, JOBROLE

-- 6. Most common WorkLifeBalance rating for those who left.

SELECT WORKLIFEBALANCE, COUNT(ATTRITION) AS EMP_LEFT FROM EMP_ATTRITION
WHERE ATTRITION = 1
GROUP BY WORKLIFEBALANCE
ORDER BY WORKLIFEBALANCE 

-- 7. Correlation-style queries: Does distance from home affect attrition?

SELECT DISTANCEFROMHOME, COUNT(ATTRITION) AS EMP_LEFT
FROM EMP_ATTRITION
WHERE ATTRITION = 1
GROUP BY DISTANCEFROMHOME
ORDER BY EMP_LEFT DESC