-- 1. How many employees left the company?

SELECT COUNT(ATTRITION) 
FROM EMP_ATTRITION
WHERE ATTRITION  = 1

-- Total Employees who have left the company = 237

-- 2. Attrition count by Department or Job Role.

SELECT DEPARTMENT, COUNT(ATTRITION) AS 'TOTAL_ATTRITION'
FROM EMP_ATTRITION
WHERE ATTRITION = 1
GROUP BY department

-- 3. Average Monthly Income of employees.

SELECT AVG(MonthlyIncome) 
FROM EMP_ATTRITION

-- Average monthly income of each employee = 6502

-- 4. Average Age of employees who left vs. who stayed.

(SELECT ATTRITION, AVG(AGE) AS AVG_AGE_EMPLOYEES
FROM EMP_ATTRITION
WHERE ATTRITION = 1
GROUP BY ATTRITION)

UNION

(SELECT ATTRITION, AVG(AGE) AS AVG_AGE_EMPLOYEES
FROM EMP_ATTRITION
WHERE ATTRITION = 0
GROUP BY ATTRITION);

-- 5. Gender-wise distribution of attrition.

(SELECT GENDER, COUNT(ATTRITION) AS EMP_LEFT
FROM EMP_ATTRITION
WHERE ATTRITION = 1
GROUP BY GENDER)


(SELECT GENDER, COUNT(ATTRITION) AS EMP_STAYED
FROM EMP_ATTRITION
WHERE ATTRITION = 0
GROUP BY GENDER)

-- 6. Count of employees by Education level.

SELECT EDUCATION AS COLLEGE_TIER, COUNT(EMPLOYEECOUNT) AS EMP_COUNT
FROM EMP_ATTRITION
GROUP BY EDUCATION
ORDER BY EDUCATION

-- 7. Top 5 job roles with the most employees.

SELECT TOP 5 JOBROLE, COUNT(EMPLOYEECOUNT) AS EMP_COUNT
FROM EMP_ATTRITION
GROUP BY JOBROLE
ORDER BY EMP_COUNT DESC